added Authorization and Heading.tsx
MiradorOne/e-cars pull request #10
Opened 2023-09-24 19:12 UTC by Adouleur

2023-10-05 13:19 UTC, MiradorOne commented
![image](https://github.com/MiradorOne/e-cars/assets/13731146/9ebebef2-0535-47d2-b757-77a68c44f546)

2023-10-05 13:20 UTC, MiradorOne commented on app/pages/ForgotPage.tsx
> +    console.log(e.target.value);
remove console.log

2023-10-05 13:20 UTC, MiradorOne commented on app/pages/LoginPage.tsx
> +    console.log(e.target.value);
same here

2023-10-05 13:20 UTC, MiradorOne commented on app/pages/SignUpPage.tsx
> +    console.log(e.target.value);
same

2023-10-05 13:21 UTC, MiradorOne requested changes
remove unnessesary .logs

2023-10-09 12:48 UTC, Adouleur commented
Done! Please check

2023-10-12 11:27 UTC, merged