Topbar and footer
MiradorOne/e-cars pull request #12
Opened 2023-10-03 10:04 UTC by Adouleur

2023-10-05 13:24 UTC, MiradorOne commented
![image](https://github.com/MiradorOne/e-cars/assets/13731146/9939b80f-3d7b-4b0f-9796-dd1b5219e0b2)
missing bottom border

2023-10-05 13:26 UTC, MiradorOne commented on app/components/layout/HamburgerMenu.tsx
> +    console.log(context?.hamburgerOpen);
remove console.log

2023-10-05 13:27 UTC, MiradorOne commented
![image](https://github.com/MiradorOne/e-cars/assets/13731146/0462ed6f-d7b4-46e1-9b52-0cadcb6ac171)
no padding

2023-10-05 13:30 UTC, MiradorOne commented on app/components/layout/Navigation.tsx
> +      <li className={liStyle}>All Cars</li>
Make all menu items as links (could be` to={'/'}`)

2023-10-05 13:31 UTC, MiradorOne commented on app/components/layout/HamburgerMenu.tsx
> +        <ShipTo isBurger={true} className="mt-6" />
All topheader icons should have` cursor: pointer` even it is not clickable right now. Or make them as` <a>` tag

2023-10-05 13:32 UTC, MiradorOne commented on app/components/layout/Socials.tsx
> +  console.log(intent);
remove

2023-10-05 13:33 UTC, MiradorOne commented on app/components/footer.tsx
> +            <p className="mb-3">About Us</p>
Should be as link. Same for bellow

2023-10-05 13:33 UTC, MiradorOne commented on app/components/footer.tsx
> +            <p className="mb-3">New cars</p>
`New cars` twice

2023-10-05 13:34 UTC, MiradorOne commented on app/components/footer.tsx
> +            <Phone fill="#767676" fillOpacity="1" className="" />
className is empty

2023-10-05 13:37 UTC, MiradorOne requested changes
fix code & ui

2023-10-05 13:52 UTC, MiradorOne commented on app/components/layout/Email.tsx
> +      <p>request@example.com</p>
<a href="mailto:request@example.com">...

2023-10-05 13:54 UTC, MiradorOne commented on app/components/layout/Phone.tsx
> +      <p>+971 55 811 9024</p>
`<a href=“tel:555-666-7777”`

2023-10-09 12:14 UTC, Adouleur commented
Done! Please check

2023-12-11 10:30 UTC, merged