About page
MiradorOne/e-cars pull request #13
Opened 2023-10-03 16:54 UTC by Adouleur

2023-10-05 13:51 UTC, MiradorOne commented on app/components/layout/Email.tsx
> +      <p>request@example.com</p>
should be `<a href="mailto:request@example.com"`

2023-10-05 13:55 UTC, MiradorOne commented on app/components/layout/Phone.tsx
> +      <p>+971 55 811 9024</p>
`<a href=“tel:555-666-7777”`

2023-10-05 13:56 UTC, MiradorOne requested changes
small fixes and g2g

2023-10-06 16:28 UTC, Adouleur commented
Done!

2023-12-11 10:31 UTC, MiradorOne commented
@Adouleur conflicts

2023-12-11 12:23 UTC, Adouleur commented
Resolved, please check @MiradorOne

2023-12-11 16:06 UTC, merged